version: '3'
services:
  teleport:
    image: <Image_Name>
    build: ./Docker_Image
    container_name: <Container_Name>
    entrypoint: /bin/sh
    hostname: OHRM-TO-DEEGHAYU
    command: -c "sleep 1 && teleport start -c /etc/teleport/teleport.yaml"
    ports:
      - "3023:3023"
      - "3024:3024"
      - "3025:3025"
      - "3080:3080"
    volumes:
      - ./config:/etc/teleport
      - ./data:/var/lib/teleport
